# Generated by Django 5.1.5 on 2025-02-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandingPageContent',
        ),
        migrations.AlterField(
            model_name='buttonclick',
            name='button_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='buttonclick',
            name='click_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
